# Generated by Django 4.1.7 on 2023-06-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('second_name', models.CharField(max_length=255, null=True)),
                ('third_name', models.CharField(max_length=255, null=True)),
                ('reference_number', models.CharField(max_length=255, null=True)),
                ('date_listed', models.DateField(null=True)),
                ('comments1', models.TextField(null=True)),
                ('designation', models.JSONField(null=True)),
                ('nationality', models.JSONField(null=True)),
                ('list_type', models.JSONField(null=True)),
                ('last_day_updated', models.JSONField(null=True)),
                ('individual_alias', models.JSONField(null=True)),
                ('individual_address', models.JSONField(null=True)),
                ('date_of_birth', models.JSONField(null=True)),
                ('place_of_birth', models.JSONField(null=True)),
                ('individual_document', models.JSONField(null=True)),
            ],
        ),
    ]
