# Generated by Django 4.1.7 on 2023-06-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanction_screener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanctionlist',
            name='date_listed',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
